@startuml
skinparam responseMessageBelowArrow true
skinparam participant {
  StereotypeFontSize 12  
}

title Process object deletion notifications

'participants
participant "NP://v1/notify-device-object-deletions" as npmsg
participant "MWDI://v1/regard-device-object-deletion" as mwdi
participant "ElasticSearch" as es
participant "MWDI://v1/notify-object-deletions" as notify
participant "XX://v1/regard-object-deletion" as subscriberOp

npmsg --> mwdi: {mount-name, counter, timestamp, objIdRef}
activate mwdi

note over subscriberOp: subscribe for updates
subscriberOp -> notify: {ownIp, ownPort, ownReceiverOperation} 
activate notify

note over mwdi: delete object from cached CC
mwdi -> es: {mount-name, path-to-target}


note over mwdi: notify subscribers
mwdi -> notify: {mount-name}
notify -> subscriberOp: {counter, timestamp, objIdRef}


@enduml