@startuml 02x_processControllerNotificationsNewDev
skinparam responseMessageBelowArrow true
skinparam participant {
  StereotypeFontSize 12  
}

title Process Controller notifications about newly connected devices

'participants
participant "NP://v1/notify-devices-newly-\nconnected-to-controller" as npmsg
participant "MWDI://v1/regard-device-newly-connected-to-controller" as mwdi
participant "ElasticSearch" as es
participant "MWDI://v1/notify-object-creations" as notify
participant "HMWDI://v1/regard-object-creation" as subscriberOp

npmsg -> mwdi: {mount-name}
activate mwdi

note over subscriberOp: subscribe for updates
subscriberOp -> notify: {ownIp, ownPort, ownReceiverOperation} 
activate notify

note over mwdi: add the device to MWDI deviceList
mwdi -> es: {mount-name}

note over mwdi: notify subscribers about the new device

mwdi o-\\o notify: {mount-name}

note over subscriberOp 
prüfen: 
- was ist der objectType = string?
  es muss ja eigentlich nur der mount-name 
  des neuen Devices geschickt werden 
- als objectIdReference müssste dann 
  eigentlich auch der mount-name ausreichen
end note

notify -> subscriberOp: {counter, timestamp, objectType, objIdReference (=mount-name)} \n




left footer 


<u> Note:</u>
\t  The objectIdReference needs to be composed of the mount-name + uuid of the related object to achieve uniqueness.
\t  However, on CC level the mount-name should already suffice.

end footer

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>



@enduml