@startuml mwdi+diagram.completeness.equipment
skinparam responseMessageBelowArrow true

title
mwdi+diagram.completeness.equipment
end title

participant "Postman" as Postman
participant "Data" as Data
participant "Collection" as Collection

group Preparation
  Data --\\o Postman : {servers, mount-name}
  activate Postman
  Postman --\\o Collection : {servers, mount-name}
end

group Equipment
  note right Postman
    t.b.d.
  end note
end

deactivate Postman

@enduml
