@startuml mwdi+diagram.invalidOrMissingRequestBody.dataprovider
skinparam responseMessageBelowArrow true

title
mwdi+testcase.invalidOrMissingRequestBody.dataprovider
end title

participant "Postman" as Postman
participant "Data" as Data
participant "Collection" as Collection

'requestBody required
participant "/v1/provide-list-of-device-interfaces" as PLODI
participant "/v1/provide-list-of-actual-device-equipment" as PLOADE
participant "/v1/provide-list-of-parallel-links" as PLOPL
participant "/v1/provide-device-status-metadata" as PDSM

'optional requestBody
participant "/v1/provide-list-of-links" as PLOL
participant "/v1/provide-data-of-all-links" as PDOAL

'no requestBody
participant "/v1/provide-list-of-connected-devices" as PLOCD
participant "/v1/provide-list-of-link-ports" as PLOLP
participant "/v1/provide-data-of-all-link-ports" as PDOALP


group Preparation
  Data --\\o Postman : {servers}
  activate Postman
  Postman --\\o Collection : {servers}
end

'-------------------------------------------------------------
== RequestBody required ==
  note over Postman, PLODI
    For each service with required requestBody there are two testcases to be executed.
    Both tests differ in the provided requestBody:
  - an invalid requestBody according to OAS
  - no requestBody provided at all
  end note

  group /v1/provide-list-of-device-interfaces
    Collection --\\o Postman : {servers}
    Postman -> PLODI : (a) {invalidRequestBody} \n(b) no requestBody
    Postman <-- PLODI : 400
    note right Postman #Orange
      check for 400
    end note
  end

  group /v1/provide-list-of-actual-device-equipment
    Collection --\\o Postman : {servers}
    Postman -> PLOADE : (a) {invalidRequestBody} \n(b) no requestBody
    Postman <-- PLOADE : 400
    note right Postman #Orange
      check for 400
    end note
  end

  group /v1/provide-list-of-parallel-links
    Collection --\\o Postman : {servers}
    Postman -> PLOPL : (a) {invalidRequestBody} \n(b) no requestBody
    Postman <-- PLOPL : 400
    note right Postman #Orange
      check for 400
    end note
  end

  group /v1/provide-device-status-metadata
    Collection --\\o Postman : {servers}
    Postman -> PDSM : (a) {invalidRequestBody} \n(b) no requestBody
    Postman <-- PDSM : (400
    note right Postman #Orange
      check for 400
    end note
  end

'-------------------------------------------------------------
== Optional requestBody == 
  group /v1/provide-list-of-links
    Collection --\\o Postman : {servers}
    Postman -> PLOL : {invalidRequestBody}
    Postman <-- PLOL : 400
    note right Postman #Orange
      check for 400
    end note
  end

  group /v1/provide-data-of-all-links
    Collection --\\o Postman : {servers}
    Postman -> PDOAL : {invalidRequestBody}
    Postman <-- PDOAL : 400
    note right Postman #Orange
      check for 400
    end note
  end


'-------------------------------------------------------------
== No requestBody == 
  group /v1/provide-list-of-connected-devices
    Collection --\\o Postman : {servers}
    Postman -> PLOCD : {dummyRequestBody}
    Postman <-- PLOCD : 200
    note right Postman #Orange
      check for 200
    end note
  end

  group /v1/provide-list-of-link-ports
    Collection --\\o Postman : {servers}
    Postman -> PLOLP : {dummyRequestBody}
    Postman <-- PLOLP : 200
    note right Postman #Orange
      check for 200
    end note
  end

  group /v1/provide-data-of-all-link-ports
    Collection --\\o Postman : {servers}
    Postman -> PDOALP : {dummyRequestBody}
    Postman <-- PDOALP : 200
    note right Postman #Orange
      check for 200
    end note
  end

deactivate Postman

@enduml
