@startuml mwdi+diagram.completeness.receiver
skinparam responseMessageBelowArrow true

title
mwdi+testcase.completeness.receiver
end title

participant "Postman" as Postman
participant "Data" as Data
participant "Collection" as Collection

participant "/v1/regard-controller-attribute-value-change" as RCAVC

group Preparation
  Data --\\o Postman : {servers, collection-input-list=(mount-name; deviceAlarm: mount-name, alarm-type-id; deviceAttributeValueChange: target, attribute-name, new-value; objectCreation: target)}
  activate Postman
  Postman --\\o Collection : {servers, collection-input-list}
end

group /v1/regard-controller-attribute-value-change
  Collection --\\o Postman : {servers}
  Postman -> RCAVC : {counter, timestamp, resource, attribute-name, new-value}
  Postman <-- RCAVC : 204
  note right Postman #Orange
    check for 204
  end note
end

deactivate Postman

@enduml
