@startuml 00x_CyclicOperationBasedDeviceListSync
skinparam responseMessageBelowArrow true

'todo: add call to /v1/provide-device-status-metadata with timestamp-filter=oldest-or-null to get the next candidate for the retrieval
'retrieval priority is no longer managed inside deviceList, but in metadata status table!

title
PromptForEmbeddingCausesCyclicLoadingOfDeviceListFromController
PromptForEmbeddingCausesCyclicLoadingOfDeviceListFromCache
PromptForEmbeddingCausesSelfCallingForLoadingOfControlConstructForDevicesNotInCache
PromptForEmbeddingCausesDeletingUnconnectedDevicesFromCache
PromptForEmbeddingCausesUpdatingMetadataTableInElasticSearchFromDeviceListSync
end title

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "ODL://{controllerInternalPathToMountPoint}?fields=\nnode(node-id;netconf-node-topology:\nconnection-status)" as odlConnectionStatus
participant "ElasticSearch://?fields=control-construct(uuid)" as ConnectedDeviceList
participant "MWDI://core-model-1-4:network-control-domain=live/control-construct={mountName}" as ControlConstruct
participant "ElasticSearch://control-construct={mountName}" as es
participant "ElasticSearch\n(metadataTable)" as mtab

ro -> mwdi
activate mwdi

note over mwdi
Cyclic operation for 
updating the internal list of devices starts
end note

note over mwdi
compare 
list from Controller & 
MWDI deviceList
end note

'get deviceList from Controller
mwdi -> odlConnectionStatus
odlConnectionStatus --> mwdi: {list of-(mount-name, connection-status)}

'get MWDI deviceList from ElasticSearch
mwdi -> ConnectedDeviceList
ConnectedDeviceList --> mwdi: {mount-name-list}

note over mwdi
repeat for all connected devices 
not in MWDI deviceList
end note

mwdi -> ControlConstruct: {mountName} (apiKeyAuth)

note over mwdi
repeat for all devices not marked
connected in list from Controller
end note

mwdi -> es: delete {mountName}

note over mwdi
  <u>UpdateMetadataTable</u>
  FOR each device that has been...
    - <b>added to deviceList</b>:
      either add it to the metadataTable, if it is not
      included yet, or update the existing entry if necessary
    - <b>deleted from deviceList</b>:
      update the metadata table
  
  (see description under <i>spec/additionalDescription/</i>
   <i>MetadataTableUpdateProcess.md</i>)
end note
mwdi -> mtab: {mount-name, <i>updateAction</i>}

deactivate mwdi

@enduml