@startuml mwdi+diagram.unknownTargetObject.receiver
skinparam responseMessageBelowArrow true

title
mwdi+testcase.unknownTargetObject.receiver
end title

participant "Postman" as Postman
participant "Data" as Data
participant "Collection" as Collection

participant "/v1/regard-controller-attribute-value-change" as RCAVC

group Preparation
  Data --\\o Postman : {servers, collection-input-list}
  activate Postman
  Postman --\\o Collection : {servers, collection-input-list}
end

group /v1/regard-controller-attribute-value-change
  Collection --\\o Postman : {servers}
  Postman -> RCAVC : {requestBody with unknown mountName in resource}
  Postman <-- RCAVC : 204
  note right Postman #Orange
    check for 204
  end note
end

deactivate Postman

@enduml
