@startuml
skinparam responseMessageBelowArrow true
skinparam guillemet [ ]
skinparam participant {
  StereotypeFontSize 12  
}

title  Periodic (DeviceList) Sync with Controller process flow


'participants
participant "RO" as ro
participant "/v1/embed-yourself" as mwdi <<mwdi-1-0-0-op-s-bm-001>>
participant "ODL://rests/data/network-topology:network-topology/\ntopology=topology-netconf?fields=\nnode(node-id;netconf-node-topology:connection-status)" as odlConnectionStatus <<mwdi-1-0-0-op-c-is-c-4-0-2-010>>
participant "ElasticSearch" as es <<mwdi-1-0-0-es-c-es-1-0-0-000>>
participant "XX://v1/regard-availability-of-new-device" as notificationToXX <<mwdi-1-0-0-op-c-is-xx-1-0-0-000>>
participant "ODL://rests/operations/network-topology:network-topology/\ntopology=topology-netconf/node={mount-name}/\nyang-ext:mount/notifications:create-subscription" as odlsubscribe1 <<mwdi-1-0-0-op-c-is-c-4-0-2-020>>
participant "ODL://rests/operations/odl-device-notification:\nsubscribe-device-notification" as odlsubscribe2 <<mwdi-1-0-0-op-c-is-c-4-0-2-021>>
participant "ODL://rests/notif/{mount-name}\n?notificationType=device" as odlsubscribe3 <<mwdi-1-0-0-op-c-is-c-4-0-2-022>>


ro -> mwdi: {RoIp, RoPort}
mwdi --> ro: {}

'get deviceList from Controller
note over mwdi: compare list from Controller\n & MWDI deviceList
mwdi -> odlConnectionStatus
odlConnectionStatus --> mwdi: {list of-(mount-name, connection-status)}

'get MWDI deviceList from ElasticSearch 
mwdi -> es: {}
es --> mwdi: {mount-name-list}

'diff both lists and process devices accordingly
note over es
 <b>action-required</b>: add or delete
 - <b>add</b>: (new device) add mount-name 
   to deviceList
 - <b>delete</b>: (disconnected device) remove 
   mount-name and related ControlConstruct
end note 

mwdi -> es: {list-of-(mount-name, action-required)}
es --> mwdi: {}

'inform subscribers about new device
note over notificationToXX: inform subscribers about new device
mwdi -> notificationToXX: {mount-name}
notificationToXX --> mwdi: {}

'subscription to Controller
note over odlsubscribe1, odlsubscribe3
<b>subscribe to device notifications</b> per relevant device:
1. create subscription stream to the device
2. subscribe to the stream
3. listen to the stream (GET)

<b>unsubscribe</b> per relevant device:
just stop listening to the notification stream (i.e. stop the GET request from step 3) for the device [the streams are managed also on the Controller,
so no DELETE here]
end note

mwdi -> odlsubscribe1: {<i>mount-name as path-parameter </i>, required-response-body}
odlsubscribe1 --> mwdi: {}

mwdi -> odlsubscribe2: {input-path-with-mount-name}
odlsubscribe2 --> mwdi: {odl-device-notification-output (contains mount-name)}

mwdi -> odlsubscribe3: {<i>mount-name as path-parameter </i>}
odlsubscribe3 --> mwdi: {parameter-update-information (includes path-to-parameter, new value, timestamp)}



left footer 


<u> Controller connection info:</u>
\t- For requesting information from other applications first <i>RO://v1/list-applications</i> would have to be executed to fetch {ApplicationName, ReleaseNumber, IpAddress, TcpPort}, 
\t  as the connection information may change during runtime.
\t-  When the MWDI sends requests to the Controller, however, this information needs to be added in the MWDI manually, because the Controller is not part of the 
\t  ApplicationFramework (no entries in RO!). 
\t-  In future releases there may be the CurrentController app which has the purpose of just providing the connection information of the Controller from within the AppFramework.
\t-  Also note: instead of providing directly the Controller connection details, the loadbalancer (distributes load across the available controller VMs) could be addressed.

<u> Notification to subscribers about new device:</u>
\t  - the subscriber app (XX, as it's not known at specification time) needs to implement <i>/v1/regard-availability-of-new-device</i>
\t  - subscriber apps can see how to do that by looking at the related callbacks in the MWDI OAS 
\t  - information about subscriber apps is stored and managed by <i>MDWI://v1/notify-availability-of-new-device</i> [mwdi-1-0-0-op-s-is-000]

<u> Device subscriptions:</u>
\t- subscriptions to the device are done according to ODL user guide: [[https://docs.opendaylight.org/projects/netconf/en/latest/user-guide.html#receiving-netconf-device-notifications-on-a-http-client]]
\t- the subscription for device changes are also managed on the Controller; once a device is removed from the Controller the related stream will also be closed; the operations are idempotent
\t- to unsubscribe just stop listening to the streams


end footer

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>

@enduml