FROM node:14

# Create app directory
WORKDIR /home/openbackhaul/microWaveDeviceInventory

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

#RUN npm install
RUN npm --proxy http://172.16.1.2:8080 --without-ssl --insecure i --only=production

# Bundle app source
COPY . .

EXPOSE 8080

#Command to start the application
CMD [ "node", "index.js" ]