FROM node:16

# Create app directory
WORKDIR /home/openbackhaul/microWaveDeviceInventory

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

ENV KAFKA_BROKER=${KAFKA_BROKER}

#RUN npm install
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 4015

#Command to start the application
CMD [ "node", "index.js" ]