openapi: 3.0.0
info:
  title: test
  version: 1.3.0

paths:
  /foo/{mountName}:
    post:
      responses:
        '204':
          description: 'foo'

components:
  parameters:
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
