@startuml 109_ProvideCacheQualityStatistics

skinparam responseMessageBelowArrow true
title  RequestForCacheQualityStatisticsCausesReadingFromElasticSearch

participant "external" as requestor
participant "MWDI://v1/provide-cache-quality-statistics" as mwdi
participant "ElasticSearch" as elastic


'POST /v1/provide-cache-quality-statistics\nRequest body with filters:\n- deviceId\n- vendor\n- deviceType\n- since\n- groupBy
activate mwdi
requestor -> mwdi : {optional filters: \n- time (date, date-since) \n- groupBy (day, deviceType, vendor) } (apiKeyAuth)

mwdi -> elastic : {optional filters}
activate elastic
elastic --> mwdi : {(filtered/grouped) statistics}
deactivate elastic


mwdi --> requestor : {(filtered/ grouped) statistics}
deactivate mwdi

@enduml
