@startuml
skinparam responseMessageBelowArrow true

title Process Controller notifications about device state changes

"RO" -> "/v1/embed-yourself": {RoIp, RoPort}
"/v1/embed-yourself" --> "RO": {}

note over "/v1/embed-yourself": create subscription stream
"/v1/embed-yourself" -> "ODL://rests/operations/sal-remote:\ncreate-data-change-event-subscription": {path, datastore, scope, notification-output-type}
"ODL://rests/operations/sal-remote:\ncreate-data-change-event-subscription" --> "/v1/embed-yourself": {sal-remote:output (stream-name)}

note over "/v1/embed-yourself": subscribe to stream
"/v1/embed-yourself" -> "ODL://rests/data/ietf-restconf-monitoring:restconf-state/streams/stream/\ndata-change-event-subscription/network-topology:network-topology/\ndatastore=OPERATIONAL/scope=SUBTREE/JSON": {}
"ODL://rests/data/ietf-restconf-monitoring:restconf-state/streams/stream/\ndata-change-event-subscription/network-topology:network-topology/\ndatastore=OPERATIONAL/scope=SUBTREE/JSON" --> "/v1/embed-yourself": {subscribe-to-notification:location}

note over "/v1/embed-yourself": receive notifications
"/v1/embed-yourself" -> "ODL://rests/notif/data-change-event-subscription/network-topology:network-topology/\ndatastore=OPERATIONAL/scope=SUBTREE/JSON": {}
"ODL://rests/notif/data-change-event-subscription/network-topology:network-topology/\ndatastore=OPERATIONAL/scope=SUBTREE/JSON" --> "/v1/embed-yourself": {streamed notification messages}


left footer \n\nSubscribe for Controller notifications about device state changes according to ODL user guide [[https://docs.opendaylight.org/projects/netconf/en/latest/user-guide.html#sse-notifications-subscription-process]].

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>


@enduml