@startuml 20x_CyclicOperationBasedDeviceListSync
skinparam responseMessageBelowArrow true

title  Cyclic Update of DeviceList

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "ODL://{mwdi-1-0-0-string-p-000}?fields=\nnode(node-id;netconf-node-topology:\nconnection-status)" as odlConnectionStatus
participant "ElasticSearch://?fields=node(node-id)" as ConnectedDeviceList
participant "MWDI://live/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct" as ControlConstruct
participant "ElasticSearch" as es

ro -> mwdi
activate mwdi

note over mwdi: compare list from Controller\n & MWDI deviceList
'get deviceList from Controller
mwdi -> odlConnectionStatus
odlConnectionStatus --> mwdi: {list of-(mount-name, connection-status)}

'get MWDI deviceList from ElasticSearch
mwdi -> ConnectedDeviceList
ConnectedDeviceList --> mwdi: {mount-name-list}

note over mwdi: repeate for devices not in MWDI deviceList
mwdi -> ControlConstruct: {mount-name} (apiKeyAuth)

note over mwdi: repeate for devices not in Controller deviceList
mwdi -> es: delete {mount-name}
deactivate mwdi

@enduml