@startuml 00x_CyclicOperationBasedDeviceListSync
skinparam responseMessageBelowArrow true

title  Cyclic Update of DeviceList

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "ODL://{mwdi-1-0-0-string-p-000}?fields=\nnode(node-id;netconf-node-topology:\nconnection-status)" as odlConnectionStatus
participant "ElasticSearch://?fields=control-construct(uuid)" as ConnectedDeviceList
participant "MWDI://core-model-1-4:network-control-domain=live/control-construct={mount-name}" as ControlConstruct
participant "ElasticSearch://control-construct={mount-name}" as es

ro -> mwdi
activate mwdi

note over mwdi: compare list from Controller\n & MWDI deviceList
'get deviceList from Controller
mwdi -> odlConnectionStatus
odlConnectionStatus --> mwdi: {list of-(mount-name, connection-status)}

'get MWDI deviceList from ElasticSearch
mwdi -> ConnectedDeviceList
ConnectedDeviceList --> mwdi: {mount-name-list}

note over mwdi: repeat for connected devices not in cache
mwdi -> ControlConstruct: {mount-name} (apiKeyAuth)

note over mwdi: repeat for devices not marked \nconnected in Controller deviceList
mwdi -> es: delete {mount-name}
deactivate mwdi

@enduml