@startuml 00x_CyclicOperationBasedDeviceStatusSync
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCausesCyclicLoadingOfDeviceStatusFromController
PromptForEmbeddingCausesCyclicLoadingOfDeviceStatusMetadataFromElasticSearch
PromptForEmbeddingCausesUpdatingDeviceStatusMetadataInElasticSearch
end title

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "ODL://{controllerInternalPathToMountPoint}?fields=\nnode(node-id;netconf-node-topology:\nconnection-status;schema-cache-directory)" as odlConnectionStatus
participant "ElasticSearch" as es

ro -> mwdi
activate mwdi

note over mwdi
Cyclic operation for 
updating the metadata table starts
end note

'get device info from Controller
note over mwdi
  <u>GetControllerDeviceInfo</u>
  get device info from Controller
end note
mwdi -> odlConnectionStatus
odlConnectionStatus -> mwdi: {list of-(mount-name, connection-status, schema-cache-directory)}

'get relevant MWDI metadata table info ElasticSearch
note over mwdi
  <u>GetMwdiMetadata</u>
  get device info metadata table
end note
mwdi -> es
es --> mwdi: {list-of(mount-name, connection-status)}

note over mwdi
<u>UpdateMetadataTable</u>:
compare devices from Controller & MWDI metadata table and
update the metadata table accordingly:
- add new devices from controller
- update device connection-status if necessary 
  (and schema-cache-directory)
- delete devices with connection-status!=connected 
  if retention period has been exceeded
end note

mwdi -> es: {list-of(mount-name, connection-status, schema-cache-directory), updateAction}
deactivate mwdi

@enduml