@startuml
skinparam responseMessageBelowArrow true

title Controller notifications informing about connection state or config changes per device

'receive the notification
"ODL:/rests/notif/{mount-name}?notificationType=device" -> "MWDI": {notification-message}
"MWDI" --> "ODL:/rests/notif/{mount-name}?notificationType=device"

note over "MWDI": message indicates: \n- connection status change \n  to "device disconnected": delete \n- config-change: update changed attribute \n  with provided value in cache
note over "ElasticSearch": action-required: delete or update, update-parameters omitted/null in case of deletion

"MWDI" --> "ElasticSearch": {mount-name, action-required, [path-to-updated-config-attribute-in-controlConstruct, updated-config-value]}
"ElasticSearch" --> "MWDI": {}

note over "MWDI": only if "device disconnected": \nunsubscribe (via DELETE)"

"MWDI" -> "ODL://rests/notif/{mount-name}\n?notificationType=device": {mount-name}
"ODL://rests/notif/{mount-name}\n?notificationType=device" --> "MWDI": {}

left footer \n\nThe subscribing to the Controller for a device is done as part of the device-list sync, this forwarding only handles unsubscribing or config change actions

@enduml