@startuml 01x_MwdiSubscribesAtNp
skinparam responseMessageBelowArrow true

title PromptForEmbeddingCausesSubscribingForNotifications

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "<i>respective</i> \n<i>ownReceiveOperation</i>" as receivers
participant "NP://v1/notify-controller-attribute-value-changes" as npnew
participant "NP://v1/notify-device-alarms" as npalarm
participant "NP://v1/notify-device-attribute-\nvalue-changes" as npattributechange
participant "NP://v1/notify-device-\nobject-creations" as npobjcreate
participant "NP://v1/notify-device-\nobject-deletions" as npobjdelete

ro -> mwdi
activate mwdi

note over mwdi: subscribe for info about \nnew and disconnected devices
mwdi -> npnew: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npnew -> receivers: {notifications} (apiKeyAuth)

note over mwdi: subscribe for info about \nalarm changes
mwdi -> npalarm: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npalarm -> receivers: {notifications} (apiKeyAuth)

note over mwdi: subscribe for info about \nattribute value changes
mwdi -> npattributechange: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npattributechange -> receivers: {notifications} (apiKeyAuth)

note over mwdi: subscribe for info about \nnew objects
mwdi -> npobjcreate: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjcreate -> receivers: {notifications} (apiKeyAuth)

note over mwdi: subscribe for info about \ndeleted objects
mwdi -> npobjdelete: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjdelete -> receivers: {notifications} (apiKeyAuth)

@enduml