@startuml 01x_MwdiSubscribesAtNp
skinparam responseMessageBelowArrow true

title PromptForEmbeddingCausesSubscribingForNotifications

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "<i>respective</i> \n<i>ownReceiveOperation</i>" as receivers
participant "NP://v1/notify-controller-attribute-value-changes" as npnew
participant "NP://v1/notify-device-alarms" as npalarm
participant "NP://v1/notify-device-attribute-value-changes" as npattributechange
participant "NP://v1/notify-device-object-creations" as npobjcreate
participant "NP://v1/notify-device-object-deletions" as npobjdelete

ro -> mwdi
activate mwdi

note over mwdi
subscribe for info about 
new and disconnected devices
end note
mwdi -> npnew: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npnew -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device alarms
end note
mwdi -> npalarm: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npalarm -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
attribute value changed notifications
end note
mwdi -> npattributechange: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npattributechange -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
object creation notifications
end note
mwdi -> npobjcreate: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjcreate -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
object deletion notifications
end note
mwdi -> npobjdelete: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjdelete -> receivers: {notifications} (apiKeyAuth)

@enduml