@startuml 01y_MwdiSubscribesAtNp
skinparam responseMessageBelowArrow true

title 
  PromptForEmbeddingCausesSubscribingForControllerNotificationsAtNP
  PromptForEmbeddingCausesSubscribingForDeviceAndAlarmNotificationsAtNP
end title

participant "RO" as ro
participant "MWDI://v1/embed-yourself" as mwdi
participant "<i>respective</i> \n<i>ownReceiveOperation</i>" as receivers
participant "NP://v1/notify-controller-attribute-value-changes" as npnew
participant "NP://v1/notify-device-alarms" as npalarm
participant "NP://v1/notify-device-attribute-value-changes" as npattributechange
participant "NP://v1/notify-device-object-creations" as npobjcreate
participant "NP://v1/notify-device-object-deletions" as npobjdelete

ro -> mwdi
activate mwdi

note over mwdi
subscribe for controller notifications, i.e.
info about new and disconnected devices
end note
mwdi -> npnew: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npnew -> receivers: {notifications} (apiKeyAuth)

note over mwdi #LightCoral
  Subscription for device and alarm notifications at NotificationProxy
  is only kept as fallback.

  <i>(It is handled via a second NP http client for which initially no</i>
  <i>real NP address information is provided; i.e. becomes only active once</i>
  <i>real NP adress information has been provided.)</i>
end note

note over mwdi
subscribe for device alarms
end note
mwdi -> npalarm: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npalarm -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
attribute value changed notifications
end note
mwdi -> npattributechange: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npattributechange -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
object creation notifications
end note
mwdi -> npobjcreate: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjcreate -> receivers: {notifications} (apiKeyAuth)

note over mwdi
subscribe for device 
object deletion notifications
end note
mwdi -> npobjdelete: {ownIp, ownPort, ownReceiveOperation} (apiKeyAuth)
npobjdelete -> receivers: {notifications} (apiKeyAuth)

@enduml