@startuml 020_NotificationBasedDeviceListSyncAdd
skinparam responseMessageBelowArrow true

title  NotifiedNewDeviceCausesSelfCallingForLoadingOfControlConstruct

participant "NP://v1/notify-controller-attribute-value-changes" as subscription
participant "MWDI://v1/regard-controller-attribute-value-change" as regardNewDevice
participant "MWDI://core-model-1-4:network-control-domain=live/control-construct={mountName}" as liveControlConstruct

subscription -> regardNewDevice: AttributeValueChangedNotification (apiKeyAuth)
activate regardNewDevice

note over regardNewDevice
IF attribute-name == 'connection-status' 
AND IF new-value == 'connected'
end note

regardNewDevice -> liveControlConstruct: {path = first part of resource incl. control-construct} (apiKeyAuth)
deactivate regardNewDevice

@enduml