@startuml 021_NotificationBasedDeviceListSyncDelete
skinparam responseMessageBelowArrow true

title  NotifiedDisconnectedDeviceCausesDeviceDeletionFromCache

participant "NP://v1/notify-controller-attribute-value-changes" as subscription
participant "MWDI://v1/regard-controller-attribute-value-change" as regardDisconnectedDevice
participant "ElasticSearch://control-construct={mountName}" as es

subscription -> regardDisconnectedDevice: notification {mount-name} (apiKeyAuth)
activate regardDisconnectedDevice

note over regardDisconnectedDevice
IF attribute-name == 'connection-status' 
AND IF new-value != 'connected'
end note

regardDisconnectedDevice -> es: delete {mount-name = value behind control-construct= in resource}
deactivate regardDisconnectedDevice

@enduml