@startuml 021_NotificationBasedDeviceListSyncDelete
skinparam responseMessageBelowArrow true

title  Notification based deleting from DeviceList

participant "NP://v1/notify-devices-newly-disconnected-from-controller" as subscription
participant "MWDI://v1/regard-device-newly-disconnected-from-controller" as regardNewDevice
participant "ElasticSearch://control-construct={mount-name}" as es

subscription -> regardNewDevice: notification {mount-name} (apiKeyAuth)
activate regardNewDevice

regardNewDevice -> es: delete {mount-name}
deactivate regardNewDevice

@enduml