@startuml 024_NotificationBasedObjectCreation
skinparam responseMessageBelowArrow true

title NotifiedDeviceObjectCreationCausesSelfCallingOfLiveResourcePath

participant "NP://v1/notify-device-object-creations" as subscription
participant "MWDI://v1/regard-device-object-creation" as regardObjectCreation
participant "ODL://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/path-to-the-object-type" as odlCreatedObject

subscription -> regardObjectCreation: {mount-name, counter, timestamp, objectType, objectIdRef} (apiKeyAuth)
activate regardObjectCreation

regardObjectCreation -> odlCreatedObject: {mount-name, objectType, objectIdRef}
odlCreatedObject --> regardObjectCreation: newly created object

@enduml