@startuml 026_NotificationBasedObjectDeletion
skinparam responseMessageBelowArrow true

title 
  NotifiedDeviceObjectDeletionCausesDeletingTheObjectInCache
  NotifiedDeviceObjectDeletionCausesMetadataUpdate
end title

participant "<i>PromptForEmbeddingCausesCyclicNotificationProcessingToCall</i>\n<i>RegardDeviceObjectDeletion</i>" as init
participant "MWDI://v1/regard-device-object-deletion" as regardObjectDeletion
participant "ElasticSearch://{resource}" as es
participant "ElasticSearch\n(deviceMetadataList)" as mtab

init -> regardObjectDeletion: {counter, timestamp, resource} (apiKeyAuth)

activate regardObjectDeletion

regardObjectDeletion -> es: delete object {path = resource, but shortened by /core-model-1-4:network-control-domain=live}

note over regardObjectDeletion
  <u>UpdateMetadata</u>
    Upon update completion of the CC data in the cache,
    update the metadata for the device
    (last-control-construct-notification-update-time,
    number-of-partial-updates-since-last-complete-update)
end note
regardObjectDeletion -> mtab: {mount-name}

deactivate regardObjectDeletion

@enduml