@startuml 026_NotificationBasedObjectDeletion
skinparam responseMessageBelowArrow true

title NotifiedDeviceObjectDeletionCausesDeletingTheObjectInCache

participant "NP://v1/notify-device-object-deletions" as subscription
participant "MWDI://v1/regard-device-object-deletion" as regardObjectDeletion
participant "ElasticSearch://{resource}" as es

subscription -> regardObjectDeletion: {counter, timestamp, resource} (apiKeyAuth)

activate regardObjectDeletion

regardObjectDeletion -> es: delete object {path = resource, but shortened by /core-model-1-4:network-control-domain=live}
deactivate regardObjectDeletion

@enduml