@startuml
skinparam responseMessageBelowArrow true

title Provide list of devices (mount-names) managed by MWDI

participant "external" as requestor
participant "MWDI://" as nodeReq
participant "ElasticSearch" as es


requestor-> nodeReq: {query-parameter: ?fields=node(node-id)}
activate nodeReq

nodeReq -> es
es --> nodeReq : {list-of-mount-names}

nodeReq --> requestor: {list-of-mount-names}
deactivate nodeReq

left footer \n\nThe path / is one level above the devices (mount-name) on the Controller, therefore it has an own forwarding. \nThe shown fields filter is mandatory for calling the service from MWDI.

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>


@enduml