@startuml
skinparam responseMessageBelowArrow true

title Provide list of devices (mount-names) managed by MWDI

participant "external" as requestor
participant "MWDI://v1/provide-list-of-connected-devices" as nodeReq
participant "ElasticSearch" as es


requestor-> nodeReq
activate nodeReq

nodeReq -> es
es --> nodeReq : {list-of-mount-names}

nodeReq --> requestor: {list-of-mount-names}
deactivate nodeReq

left footer \n\n - The MWDI only has cached data for devices, which are currently connected on the Controller. \n - The HMWDI and Controller also cover devices which are in connecting or unable-to-connect state.

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>


@enduml