@startuml
skinparam responseMessageBelowArrow true

title All RessourcePath-Requests cause reading from ElasticSearch DB

"external" -> "<all control-construct ressource paths: \n/node={mount-name}/yang-ext:mount/\ncore-model-1-4:control-construct/...>": {mount-name, list-of-other-parameters-relevant-to-respective-path}

"<all control-construct ressource paths: \n/node={mount-name}/yang-ext:mount/\ncore-model-1-4:control-construct/...>" -> "ElasticSearch": {mount-name, path-to-relevant-data-set-including-relevant-parameters}
"ElasticSearch" --> "<all control-construct ressource paths: \n/node={mount-name}/yang-ext:mount/\ncore-model-1-4:control-construct/...>": {ControlConstruct-data-subset}

"<all control-construct ressource paths: \n/node={mount-name}/yang-ext:mount/\ncore-model-1-4:control-construct/...>" --> "external": {ControlConstruct-data-subset}


left footer \nPossibly need to create an own separate forwarding for each ressource path request

<style>
footer {
  HorizontalAlignment left
  FontSize 12
}
</style>

@enduml