@startuml 100_provideListOfDeviceInterfaces
skinparam responseMessageBelowArrow true

title  provideListOfDeviceInterfaces

participant "external" as requestor
participant "MWDI://v1/provide-list-of-device-interfaces" as provideListOfDeviceInterfaces
participant "ElasticSearch://control-construct={mount-name}?fields=fields=logical-termination-point(uuid;layer-protocol(local-id;layer-protocol-name))" as DeviceInterfaceList

requestor -> provideListOfDeviceInterfaces: (apiKeyAuth)
activate provideListOfDeviceInterfaces

provideListOfDeviceInterfaces -> DeviceInterfaceList
DeviceInterfaceList --> provideListOfDeviceInterfaces: {device-interface-list}

provideListOfDeviceInterfaces --> requestor: {device-interface-list}
deactivate provideListOfDeviceInterfaces

@enduml