@startuml 101_provideListOfDeviceInterfaces
skinparam responseMessageBelowArrow true

title  RequestForListOfDeviceInterfacesCausesReadingFromCache

participant "external" as requestor
participant "MWDI://v1/provide-list-of-device-interfaces" as provideListOfDeviceInterfaces
participant "ElasticSearch://control-construct={mountName}?fields=fields=logical-termination-point(uuid;layer-protocol(local-id;layer-protocol-name))" as DeviceInterfaceList

requestor -> provideListOfDeviceInterfaces: {mount-name} (apiKeyAuth)
activate provideListOfDeviceInterfaces

provideListOfDeviceInterfaces -> DeviceInterfaceList
DeviceInterfaceList --> provideListOfDeviceInterfaces: {list of {uuid, local-id, layer-protocol-name}}

provideListOfDeviceInterfaces --> requestor: {list of {uuid, local-id, layer-protocol-name}}
deactivate provideListOfDeviceInterfaces

@enduml