@startuml 100_provideListOfActualDeviceEquipment
skinparam responseMessageBelowArrow true

title  provideListOfActualDeviceEquipment

participant "external" as requestor
participant "MWDI://v1/provide-list-of-device-interfaces" as provideListOfActualDeviceEquipment
participant "ElasticSearch://control-construct={mount-name}?fields=top-level-equipment;equipment(uuid;actual-equipment(manufactured-thing(equipment-type(type-name))))" as ActualDeviceEquipmentList

requestor -> provideListOfActualDeviceEquipment: (apiKeyAuth)
activate provideListOfActualDeviceEquipment

provideListOfActualDeviceEquipment -> ActualDeviceEquipmentList
ActualDeviceEquipmentList --> provideListOfActualDeviceEquipment: {actual-device-equipment-list}

provideListOfActualDeviceEquipment --> requestor: {actual-device-equipment-list}
deactivate provideListOfActualDeviceEquipment

@enduml