@startuml 103_ProvideListOfParallelLinks
skinparam responseMessageBelowArrow true

title  RequestForListOfParallelLinksCauses

participant "external" as requestor
participant "MWDI://v1/provide-list-of-parallel-links" as provideListOfParallelLinks
participant "ElasticSearch://link={uuid}" as Link
participant "ElasticSearch://link={uuid}" as Link

requestor -> provideListOfParallelLinks: {link-id}(apiKeyAuth)

note over provideListOfParallelLinks 
<u> ReadingEndpointsFromCache </u>
end note
activate provideListOfParallelLinks
provideListOfParallelLinks -> Link : {uuid=link-id}
Link --> provideListOfParallelLinks: {given-layer-protocol-name, given-list-of-fd}

note over provideListOfParallelLinks
<u> SearchingParallelLinksInCache </u>
Filter all Links in Cache for:
  (layer-protocol-name == given-layer-protocol-name)
  AND (elements of given-list-of-fd also elements of list-of-fd)
end note
provideListOfParallelLinks -> Link : {uuid=*}
Link --> provideListOfParallelLinks:

provideListOfParallelLinks --> requestor: {list of {link-id}}
deactivate provideListOfParallelLinks

@enduml