@startuml 108_ProvideDeviceMetadataTable
skinparam responseMessageBelowArrow true

title RequestForDeviceStatusMetadataCausesReadingFromElasticSearch

participant "external" as requestor
participant "MWDI://v1/provide-device-status-metadata" as data
participant "ElasticSearch" as es

requestor -> data: {(optional) mount-name-list} (apiKeyAuth)
activate data

note over es
  Optionally the metadata service can be called with
  a mount-name-list (requestBody).
  If such a list is provided, the metadata table
  content is filtered for devices from this list.
end note

data -> es: {(optional) mount-name-list}
es -> data: {(filtered) metadataTable}

data -> requestor: {(filtered) metadataTable}
deactivate data

@enduml