@startuml
skinparam responseMessageBelowArrow true
skinparam participant {
  StereotypeFontSize 12  
}

title Process device alarm notifications

'participants
participant "NP://v1/notify-device-alarms" as npmsg
participant "MWDI://v1/regard-device-alarm" as mwdi
participant "<i>possible alarms</i> \n<i>retrieval from ODL</i>" as odl
participant "ElasticSearch" as es
participant "MWDI://v1/notify-alarms" as notify
participant "XX://v1/regard-alarm" as subscriberOp

npmsg --> mwdi: {mount-name, alarmEventSequenceNumber, alarmTypeId,\nalarmTypQualifier, resource, problemSeverity, timestamp}
activate mwdi

note over subscriberOp: subscribe for updates
subscriberOp -> notify: {ownIp, ownPort, ownReceiverOperation} 
activate notify

note over mwdi: <b>todo - check if msg information suffices</b>

' if not sufficient, retrieve again from controller
note over mwdi, odl: case: not sufficient
mwdi -> odl: {path-derived-from-notification-data}
odl --> mwdi: {currentAlarms-from-device}

note over mwdi: update the CC cache
mwdi -> es: {mount-name, path-to-target-object, up-to-date-currentAlarms}


note over mwdi: notify subscribers
mwdi -> notify: {mount-name}
notify -> subscriberOp: {alarmEventSequenceNumber, alarmTypeId,\nalarmTypQualifier, resource, problemSeverity, timestamp}



left footer 

<u> To check:</u>
\t  It needs to be checked whether the MWDI 
    - (a) can update the cached CurrentAlarms list on its own with the information in the notification or
    - (b) needs to retrieve the respective current alarms block from the Controller
Afterwards the currentAlarms must look as they are on the device

<u> Note:</u>
\t  The objectIdReference needs to be composed of the mount-name + uuid of the related object to achieve uniqueness.
\t  However, on CC level the mount-name should already suffice.

\t  Currently the HMWDI is the only subscriber, and it shall not delete it's stored device data if the device is disconnected.
\t  Therefore HMWDI might not need to subscribe to this notification.

end footer

<style>
footer {
  HorizontalAlignment left
  FontSize 14
}
</style>


@enduml