@startuml 110_ProvideListOfCachedDevices
skinparam responseMessageBelowArrow true

title RequestForListOfCachedDevicesCausesReadingFromCache

participant "external" as requestor
participant "MWDI://v1/provide-list-of-cached-devices" as mwdi
participant "ElasticSearch \n(deviceMetadataList)" as deviceList

requestor -> mwdi: (apiKeyAuth)
activate mwdi

mwdi -> deviceList
deviceList --> mwdi: {list-of(mount-name, connection-status)}

mwdi --> requestor: {list-of(mount-name, connection-status)}
deactivate mwdi

@enduml