@startuml 120_MwdiNotifiesAttributeChange
skinparam responseMessageBelowArrow true

title 
MWDI notifies a change to an Attribute in its Cache
SubscribingAtMwdiForDeviceAttributeChangesCausesSendingNotifications
end title

participant "external (Requestor)" as external
participant "Requestor://receive-operation" as receiverOperation
participant "MWDI://v1/notify-attribute-value-changes" as notifyAttributeChange

external -> notifyAttributeChange: {ownIp, ownPort, ownReceiverOperation} (apiKeyAuth)
activate notifyAttributeChange

note over notifyAttributeChange: operation that changes an attribute in ElasticSearch

notifyAttributeChange -> receiverOperation: notification {counter, timestamp, reseource, attributeName, newValue} (apiKeyAuth)
deactivate notifyAttributeChange

@enduml