@startuml 122_MwdiNotifiesObjectDeletion
skinparam responseMessageBelowArrow true

title 
MWDI notifies an Object being deleted in its Cache
SubscribingAtMwdiForDeviceObjectDeletionsCausesSendingNotifications
end title

participant "external (Requestor)" as external
participant "Requestor://receive-operation" as receiverOperation
participant "MWDI://v1/notify-object-deletions" as notifyObjectDeletion

external -> notifyObjectDeletion: {ownIp, ownPort, ownReceiverOperation} (apiKeyAuth)
activate notifyObjectDeletion

note over notifyObjectDeletion: operation that deletes an object in ElasticSearch

notifyObjectDeletion -> receiverOperation: notification {counter, timestamp, resource} (apiKeyAuth)
deactivate notifyObjectDeletion

@enduml