@startuml
skinparam responseMessageBelowArrow true


title Process object creation notifications

'participants
participant "NP://v1/notify-device-object-creations" as npmsg
participant "MWDI://v1/regard-device-object-creation" as mwdi
participant "ElasticSearch" as es
participant "MWDI://v1/notify-object-creations" as notify
participant "XX://v1/regard-object-creation" as subscriberOp

npmsg --> mwdi: {mount-name, counter, timestamp, objectType, objIdRef}
activate mwdi

note over subscriberOp: subscribe for updates
subscriberOp -> notify: {ownIp, ownPort, ownReceiverOperation} 
activate notify

note over mwdi: update the CC cache
mwdi -> es: {mount-name, path-to-target, new-object}


note over mwdi: notify subscribers
mwdi -> notify: {mount-name}
notify -> subscriberOp: {counter, timestamp, objectType, objIdRef}


@enduml