@startuml 201_CacheRessourcePath
skinparam responseMessageBelowArrow true

title  Retrieval of cached ControlConstruct classes

participant "external" as requestor
participant "MWDI://cache/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/<i>path-to-class</i>" as CacheControlConstructClass
participant "ElasticSearch://node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/<i>path-to-class</i>" as EsControlConstructClass

note over CacheControlConstructClass: <i>specific-path-parameters</i> can include \nfields filter to retrieve only specific attributes
requestor -> CacheControlConstructClass: {mount-name, specific-path-parameters} (apiKeyAuth)
activate CacheControlConstructClass

CacheControlConstructClass -> EsControlConstructClass: {mount-name, specific-path-parameters}
EsControlConstructClass --> CacheControlConstructClass: {control-construct-class-or-attributes}

CacheControlConstructClass --> requestor: {control-construct-class-or-attributes}
deactivate CacheControlConstructClass

@enduml