@startuml 50x_LiveControlConstruct
skinparam responseMessageBelowArrow true

title  External, cyclic operation or notification driven retrieving of Live ControlConstruct

participant "external, cyclic operation \n or notification based" as requestor
participant "MWDI://live/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct" as LiveControlConstruct
participant "ODL:/{mwdi-1-0-0-string-p-000}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct" as OdlControlConstruct
participant "ElasticSearch://node={mount-name}/yang-ext:mount/core-model-1-4:control-construct" as EsControlConstruct

requestor -> LiveControlConstruct: {mount-name} (apiKeyAuth)
activate LiveControlConstruct

LiveControlConstruct -> OdlControlConstruct: {mount-name}
OdlControlConstruct --> LiveControlConstruct: {control-construct}

LiveControlConstruct -> EsControlConstruct: {mount-name, control-construct}

LiveControlConstruct --> requestor: {control-construct}
deactivate LiveControlConstruct

skinparam NoteBackgroundColor salmon
note over requestor: Requestor has to wait \nfor a very long time for \na response. Does this work?
skinparam NoteBackgroundColor default

@enduml